version: 2

models:
  - name: dim_listings_cleansed
    columns:

      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
         - not_null
         - relationships:
             to: ref('dim_hosts_cleansed')
             field: host_id

      - name: room_type
        tests:
         - accepted_values:
             values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
  - name: dim_hosts_cleansed
    description: list of hosts by name with super hosts denoted
    columns:
    
      - name: host_id
        description: the unique id of the host
        tests:
          - not_null
          - unique

      - name: host_name
        description: the name of the host with null values replaced with 'anonymous'

      - name: is_superhost
        description: demarks if the host is a superhost (true/false)

    
